const SupportCode = require('../../../common/support-code');

module.exports = {
	'0000': new SupportCode('MY_SUCCESS', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0001': new SupportCode('MAIL_ADDRESS_NOT_CONFIRMED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0500': new SupportCode('LIBRARY_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0501': new SupportCode('NOT_INITIALIZED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0502': new SupportCode('ALREADY_INITIALIZED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0511': new SupportCode('BUSY', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0591': new SupportCode('NOT_IMPLEMENTED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0592': new SupportCode('DEPRECATED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0593': new SupportCode('DEVELOPMENT_ONLY', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0600': new SupportCode('INVALID_ARGUMENT', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0601': new SupportCode('INVALID_POINTER', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0602': new SupportCode('OUT_OF_RANGE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0603': new SupportCode('INVALID_SIZE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0604': new SupportCode('INVALID_FORMAT', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0605': new SupportCode('INVALID_HANDLE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0606': new SupportCode('INVALID_VALUE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0700': new SupportCode('INTERNAL_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0701': new SupportCode('END_OF_STREAM', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0710': new SupportCode('FILE_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0711': new SupportCode('FILE_NOT_FOUND', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0712': new SupportCode('FILE_VERSION_MISMATCH', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0713': new SupportCode('FILE_IO_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0714': new SupportCode('FILE_TYPE_MISMATCH', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0730': new SupportCode('OUT_OF_RESOURCE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0731': new SupportCode('SHORT_OF_BUFFER', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0740': new SupportCode('OUT_OF_MEMORY', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0741': new SupportCode('OUT_OF_GLOBAL_HEAP', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0742': new SupportCode('OUT_OF_CROSS_PROCESS_HEAP', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0743': new SupportCode('OUT_OF_PROCESS_LOCAL_HEAP', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0744': new SupportCode('OUT_OF_MXML_HEAP', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0800': new SupportCode('UC_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0801': new SupportCode('UC_OPEN_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0802': new SupportCode('UC_READ_SYS_CONFIG_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0810': new SupportCode('MCP_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0811': new SupportCode('MCP_OPEN_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0812': new SupportCode('MCP_GET_INFO_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0820': new SupportCode('ISO_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0821': new SupportCode('ISO_INIT_FAILURE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0822': new SupportCode('ISO_GET_COUNTRY_CODE_FAILURE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0823': new SupportCode('ISO_GET_LANGUAGE_CODE_FAILURE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0850': new SupportCode('MXML_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0900': new SupportCode('IOS_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0901': new SupportCode('IOS_OPEN_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'1000': new SupportCode('ACCOUNT_MANAGEMENT_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'1001': new SupportCode('ACCOUNT_NOT_FOUND', 'Missing description', 'Unable to find the specified user.', 'Missing fix', 'Missing link'),
	'1002': new SupportCode('SLOTS_FULL', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'1011': new SupportCode('ACCOUNT_NOT_LOADED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'1012': new SupportCode('ACCOUNT_ALREADY_LOADED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'1013': new SupportCode('ACCOUNT_LOCKED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'1021': new SupportCode('NOT_NETWORK_ACCOUNT', 'Missing description', 'Use of this feature requires a linked\nNintendo Network ID.\n\nYou can link an ID from User Settings.', 'Missing fix', 'Missing link'),
	'1022': new SupportCode('NOT_LOCAL_ACCOUNT', 'Missing description', 'The current user already has\na Nintendo Network ID.', 'Missing fix', 'Missing link'),
	'1023': new SupportCode('ACCOUNT_NOT_COMMITTED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'1101': new SupportCode('NETWORK_CLOCK_INVALID', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'1999': new SupportCode('Missing name', 'Missing description', 'An error has occurred.\n\nPlease turn off the Wii U console\nand try again.\n\nIf the problem persists, please\nmake a note of the error code and\nvisit support.nintendo.com.', 'Missing fix', 'Missing link'),
	'2000': new SupportCode('AUTHENTICATION_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2100': new SupportCode('HTTP_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2101': new SupportCode('HTTP_UNSUPPORTED_PROTOCOL', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2102': new SupportCode('HTTP_FAILED_INIT', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2103': new SupportCode('HTTP_URL_MALFORMAT', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2104': new SupportCode('HTTP_NOT_BUILT_IN', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2105': new SupportCode('HTTP_COULDNT_RESOLVE_PROXY', 'Missing description', 'Unable to connect to the proxy server.\n\nPlease check that the proxy-server\nsettings on your Wii U console are\ncorrect.\n\nTo do so, select System Settings ⇒\nInternet ⇒ Connect to the Internet, and\nthen open the Connections list. Next,\nselect the appropriate network from that\nlist, and then select Change Settings ⇒\nProxy Settings to check your settings.\n\nIf it is not possible to connect using\na PC or other device with the same\nsettings, the settings on the proxy\nserver itself may be incorrect, so\nplease check them as well.', 'Missing fix', 'Missing link'),
	'2106': new SupportCode('HTTP_COULDNT_RESOLVE_HOST', 'Missing description', 'Unable to connect to the Internet.\n\nThe network may be busy.\nPlease try again later.\n\nIf you are using a Wi-Fi network,\nthe signal strength may be poor.\nPlease make sure there are no\nobstructions between the console\nand network device, and then try\nagain.\n\nIf this problem persists, please check\nwhether or not you can connect to\nthe Internet from a PC or other\ndevice using the same settings.', 'Missing fix', 'Missing link'),
	'2107': new SupportCode('HTTP_COULDNT_CONNECT', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2108': new SupportCode('HTTP_FTP_WEIRD_SERVER_REPLY', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2109': new SupportCode('HTTP_REMOTE_ACCESS_DENIED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2110': new SupportCode('HTTP_OBSOLETE10', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2111': new SupportCode('HTTP_FTP_WEIRD_PASS_REPLY', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2112': new SupportCode('HTTP_OBSOLETE12', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2113': new SupportCode('HTTP_FTP_WEIRD_PASV_REPLY', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2114': new SupportCode('HTTP_FTP_WEIRD_227_FORMAT', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2115': new SupportCode('HTTP_FTP_CANT_GET_HOST', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2116': new SupportCode('HTTP_OBSOLETE16', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2117': new SupportCode('HTTP_FTP_COULDNT_SET_TYPE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2118': new SupportCode('HTTP_PARTIAL_FILE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2119': new SupportCode('HTTP_FTP_COULDNT_RETR_FILE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2120': new SupportCode('HTTP_OBSOLETE20', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2121': new SupportCode('HTTP_QUOTE_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2122': new SupportCode('HTTP_HTTP_RETURNED_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2123': new SupportCode('HTTP_WRITE_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2124': new SupportCode('HTTP_OBSOLETE24', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2125': new SupportCode('HTTP_UPLOAD_FAILED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2126': new SupportCode('HTTP_READ_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2127': new SupportCode('HTTP_OUT_OF_MEMORY', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2128': new SupportCode('HTTP_OPERATION_TIMEDOUT', 'Missing description', 'Unable to connect to the server.\n\nEither the server is experiencing high\ntraffic volumes or a server error has\noccurred. Please try again later.\n\nTo learn more about the server\'s current\nstatus, visit support.nintendo.com.\n\nIf you are using a Wi-Fi network, the\nsignal strength may be too poor. Please\nmove the console closer to the network\ndevice, make sure that there are no\nobstructions between the two, and then\ntry again.\n\nIf this problem persists, please check\nwhether or not you can connect to the\nInternet from a PC or other device using\nthe same settings.', 'Missing fix', 'Missing link'),
	'2129': new SupportCode('HTTP_OBSOLETE29', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2130': new SupportCode('HTTP_FTP_PORT_FAILED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2131': new SupportCode('HTTP_FTP_COULDNT_USE_REST', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2132': new SupportCode('HTTP_OBSOLETE32', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2133': new SupportCode('HTTP_RANGE_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2134': new SupportCode('HTTP_HTTP_POST_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2135': new SupportCode('HTTP_SSL_CONNECT_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2136': new SupportCode('HTTP_BAD_DOWNLOAD_RESUME', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2137': new SupportCode('HTTP_FILE_COULDNT_READ_FILE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2138': new SupportCode('HTTP_LDAP_CANNOT_BIND', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2139': new SupportCode('HTTP_LDAP_SEARCH_FAILED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2140': new SupportCode('HTTP_OBSOLETE40', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2141': new SupportCode('HTTP_FUNCTION_NOT_FOUND', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2142': new SupportCode('HTTP_ABORTED_BY_CALLBACK', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2143': new SupportCode('HTTP_BAD_FUNCTION_ARGUMENT', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2144': new SupportCode('HTTP_OBSOLETE44', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2145': new SupportCode('HTTP_INTERFACE_FAILED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2146': new SupportCode('HTTP_OBSOLETE46', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2147': new SupportCode('HTTP_TOO_MANY_REDIRECTS', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2148': new SupportCode('HTTP_UNKNOWN_OPTION', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2149': new SupportCode('HTTP_TELNET_OPTION_SYNTAX', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2150': new SupportCode('HTTP_OBSOLETE50', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2151': new SupportCode('HTTP_PEER_FAILED_VERIFICATION', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2152': new SupportCode('HTTP_GOT_NOTHING', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2153': new SupportCode('HTTP_SSL_ENGINE_NOTFOUND', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2154': new SupportCode('HTTP_SSL_ENGINE_SETFAILED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2155': new SupportCode('HTTP_SEND_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2156': new SupportCode('HTTP_RECV_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2157': new SupportCode('HTTP_OBSOLETE57', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2158': new SupportCode('HTTP_SSL_CERTPROBLEM', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2159': new SupportCode('HTTP_SSL_CIPHER', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2160': new SupportCode('HTTP_SSL_CACERT', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2161': new SupportCode('HTTP_BAD_CONTENT_ENCODING', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2162': new SupportCode('HTTP_LDAP_INVALID_URL', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2163': new SupportCode('HTTP_FILESIZE_EXCEEDED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2164': new SupportCode('HTTP_USE_SSL_FAILED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2165': new SupportCode('HTTP_SEND_FAIL_REWIND', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2166': new SupportCode('HTTP_SSL_ENGINE_INITFAILED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2167': new SupportCode('HTTP_LOGIN_DENIED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2168': new SupportCode('HTTP_TFTP_NOTFOUND', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2169': new SupportCode('HTTP_TFTP_PERM', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2170': new SupportCode('HTTP_REMOTE_DISK_FULL', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2171': new SupportCode('HTTP_TFTP_ILLEGAL', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2172': new SupportCode('HTTP_TFTP_UNKNOWNID', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2173': new SupportCode('HTTP_REMOTE_FILE_EXISTS', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2174': new SupportCode('HTTP_TFTP_NOSUCHUSER', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2175': new SupportCode('HTTP_CONV_FAILED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2176': new SupportCode('HTTP_CONV_REQD', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2177': new SupportCode('HTTP_SSL_CACERT_BADFILE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2178': new SupportCode('HTTP_REMOTE_FILE_NOT_FOUND', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2179': new SupportCode('HTTP_SSH', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2180': new SupportCode('HTTP_SSL_SHUTDOWN_FAILED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2181': new SupportCode('HTTP_AGAIN', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2182': new SupportCode('HTTP_SSL_CRL_BADFILE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2183': new SupportCode('HTTP_SSL_ISSUER_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2184': new SupportCode('HTTP_FTP_PRET_FAILED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2185': new SupportCode('HTTP_RTSP_CSEQ_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2186': new SupportCode('HTTP_RTSP_SESSION_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2187': new SupportCode('HTTP_FTP_BAD_FILE_LIST', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2188': new SupportCode('HTTP_CHUNK_FAILED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2189': new SupportCode('HTTP_NSSL_NO_CTX', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2210': new SupportCode('SO_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2211': new SupportCode('SO_SELECT_ERROR', 'Missing description', 'Unable to connect to the Internet.\n\nPlease try again later.\n\nIf you are using a Wi-Fi network, the\nsignal strength may be poor. Please\nmake sure there are no obstructions\nbetween the console and network\ndevice, and then try again.\n\nIf this problem persists, please check\nwhether or not you can connect to the\nInternet from a PC or other device\nusing the same settings.', 'Missing fix', 'Missing link'),
	'2400': new SupportCode('REQUEST_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2401': new SupportCode('BAD_FORMAT_PARAMETER', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2402': new SupportCode('BAD_FORMAT_REQUEST', 'The HTTP request contained invalid data', 'Missing message', 'Try again later or try a different input', 'Missing link'),
	'2403': new SupportCode('REQUEST_PARAMETER_MISSING', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2404': new SupportCode('WRONG_HTTP_METHOD', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2420': new SupportCode('RESPONSE_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2421': new SupportCode('BAD_FORMAT_RESPONSE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2422': new SupportCode('RESPONSE_ITEM_MISSING', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2423': new SupportCode('RESPONSE_TOO_LARGE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2441': new SupportCode('NOT_MODIFIED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2450': new SupportCode('INVALID_COMMON_PARAMETER', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2451': new SupportCode('INVALID_PLATFORM_ID', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2452': new SupportCode('UNAUTHORIZED_DEVICE', 'The device you are using was not authorized to make the request', 'Missing message', 'Try again later or on a different device', 'Missing link'),
	'2453': new SupportCode('INVALID_SERIAL_ID', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2454': new SupportCode('INVALID_MAC_ADDRESS', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2455': new SupportCode('INVALID_REGION', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2456': new SupportCode('INVALID_COUNTRY', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2457': new SupportCode('INVALID_LANGUAGE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2458': new SupportCode('UNAUTHORIZED_CLIENT', 'The HTTP client was not authorized to make the request', 'Unable to connect to the server.\n\nEither the server is experiencing high\ntraffic volumes or a server error has\noccurred. Please try again later.\n\nTo learn more about the server\'s current\nstatus, visit support.nintendo.com.', 'Try again later or on a different device', 'Missing link'),
	'2459': new SupportCode('DEVICE_ID_EMPTY', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2460': new SupportCode('SERIAL_ID_EMPTY', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2461': new SupportCode('PLATFORM_ID_EMPTY', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2471': new SupportCode('INVALID_UNIQUE_ID', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2472': new SupportCode('INVALID_CLIENT_ID', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2473': new SupportCode('INVALID_CLIENT_KEY', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2481': new SupportCode('INVALID_NEX_CLIENT_ID', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2482': new SupportCode('INVALID_GAME_SERVER_ID', 'The game server requested could not be found. Either the game is not supported or is tester-only', 'Missing message', 'Check to see if your game is supported at https://pretendo.network/progress. If you\'re a tester, check your account is set to Beta at https://pretendo.network/account', 'Missing link'),
	'2483': new SupportCode('GAME_SERVER_ID_ENVIRONMENT_NOT_FOUND', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2484': new SupportCode('GAME_SERVER_ID_UNIQUE_ID_NOT_LINKED', 'The game server ID and title ID were not linked, or the request did not send a game server ID. This error should never happen normally', 'Missing message', 'File a bug report with as much detail as possible at https://github.com/PretendoNetwork/account/issues/new', 'Missing link'),
	'2485': new SupportCode('CLIENT_ID_UNIQUE_ID_NOT_LINKED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2501': new SupportCode('DEVICE_MISMATCH', 'The console certificate sent in the request was invalid or missing', 'This Nintendo Network ID cannot\nbe used on this console.', 'Ensure your console certificate is untampered with and try again later. If using Cemu, dump your system files again', 'Missing link'),
	'2502': new SupportCode('COUNTRY_MISMATCH', 'Missing description', 'Online features cannot be used because\nthe country settings on the Wii U\nconsole and the Nintendo Network ID\ndo not match.\n\nCheck the Wii U System Settings to\nensure that your country of residence\nhas been selected under country\nsettings. \n\nIf the country setting is correct, create\na new user on the Wii U and link it to a\nNintendo Network ID that is valid in\nyour country of residence.', 'Missing fix', 'Missing link'),
	'2503': new SupportCode('EULA_NOT_ACCEPTED', 'Missing description', 'To use online services, you must\naccept the terms of the Network\nServices Agreement.\n\nGo to the Wii U Menu and select User\nSettings to agree to the latest terms.', 'Missing fix', 'Missing link'),
	'2510': new SupportCode('UPDATE_REQUIRED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2511': new SupportCode('SYSTEM_UPDATE_REQUIRED', 'Your console is not up to date', 'In order to use online services, a\nsystem update is required.\n\nGo to System Settings to perform a\nsystem update.', 'Update your console', 'Missing link'),
	'2512': new SupportCode('APPLICATION_UPDATE_REQUIRED', 'Your game is not up to date', 'This software must be updated before\nonline services can be used.\n\nTo update the software, go to the Wii U\nMenu and then start the software again.', 'Update your game', 'Missing link'),
	'2520': new SupportCode('UNAUTHORIZED_REQUEST', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2521': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2522': new SupportCode('REQUEST_FORBIDDEN', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2530': new SupportCode('RESOURCE_NOT_FOUND', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2531': new SupportCode('PID_NOT_FOUND', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2532': new SupportCode('NEX_ACCOUNT_NOT_FOUND', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2533': new SupportCode('GENERATE_TOKEN_FAILURE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2534': new SupportCode('REQUEST_NOT_FOUND', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2535': new SupportCode('MASTER_PIN_NOT_FOUND', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2536': new SupportCode('MAIL_TEXT_NOT_FOUND', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2537': new SupportCode('SEND_MAIL_FAILURE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2538': new SupportCode('APPROVAL_ID_NOT_FOUND', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2540': new SupportCode('INVALID_EULA_PARAMETER', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2541': new SupportCode('INVALID_EULA_COUNTRY', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2542': new SupportCode('INVALID_EULA_COUNTRY_AND_VERSION', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2543': new SupportCode('EULA_NOT_FOUND', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2570': new SupportCode('PHRASE_NOT_ACCEPTABLE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2571': new SupportCode('ACCOUNT_ID_ALREADY_EXISTS', 'You are trying to create a PNID using a username that is either already in use by another Pretendo user, or is used by a different NNID on your console', 'The Nintendo Network ID you entered\nis already in use.\n\nPlease enter a different ID.', 'Choose a different username', 'Missing link'),
	'2572': new SupportCode('ACCOUNT_ID_NOT_ACCEPTABLE', 'The username you entered contains rejected text', 'The Nintendo Network ID you entered\nincludes text that cannot be used.\n\nPlease enter a different ID.', 'Choose a different username', 'Missing link'),
	'2573': new SupportCode('ACCOUNT_PASSWORD_NOT_ACCEPTABLE', 'The password entered did not follow the instructions', 'The password you entered\ncannot be used.\n\nPlease try again, following the\ninstructions on your TV screen.', 'Choose a different password', 'Missing link'),
	'2574': new SupportCode('MII_NAME_NOT_ACCEPTABLE', 'The Mii nickname you entered contains rejected text', 'The nickname you entered\ncannot be used.', 'Choose a different nickname', 'Missing link'),
	'2575': new SupportCode('MAIL_ADDRESS_NOT_ACCEPTABLE', 'Invalid email address entered', 'The e-mail address you entered is not\ncorrect.\n\nPlease check the e-mail address\nyou entered and try again.', 'Enter a valid email address', 'Missing link'),
	'2576': new SupportCode('ACCOUNT_ID_FORMAT_INVALID', 'Missing description', 'The Nintendo Network ID you\nentered cannot be used.\n\nPlease try again, following the\ninstructions on your TV screen.', 'Missing fix', 'Missing link'),
	'2577': new SupportCode('ACCOUNT_ID_PASSWORD_SAME', 'Your username and password are the same', 'Your Nintendo Network ID and\npassword are the same.\n\nPlease use a different password.', 'Change either your username or password', 'Missing link'),
	'2578': new SupportCode('ACCOUNT_ID_CHAR_NOT_ACCEPTABLE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2579': new SupportCode('ACCOUNT_ID_SUCCESSIVE_SYMBOL', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2580': new SupportCode('ACCOUNT_ID_SYMBOL_POSITION_NOT_ACCEPTABLE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2581': new SupportCode('ACCOUNT_ID_TOO_MANY_DIGIT', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2582': new SupportCode('ACCOUNT_PASSWORD_CHAR_NOT_ACCEPTABLE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2583': new SupportCode('ACCOUNT_PASSWORD_TOO_FEW_CHAR_TYPES', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2584': new SupportCode('ACCOUNT_PASSWORD_SUCCESSIVE_SAME_CHAR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2585': new SupportCode('MAIL_ADDRESS_DOMAIN_NAME_NOT_ACCEPTABLE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2586': new SupportCode('MAIL_ADDRESS_DOMAIN_NAME_NOT_RESOLVED', 'The email address entered uses a domain which could not be located', 'Missing message', 'Enter a different email address', 'Missing link'),
	'2587': new SupportCode('Missing name', 'Missing description', 'The Nintendo Network ID you entered\nalready exists.\n\nIf you want to use this ID, select "Link a\nNintendo Network ID" in User Settings,\nand follow the on-screen instructions.\n\nDuring the process, select "Yes" when\nasked "Do you have a Nintendo Network\nID?" You will need to enter the e-mail\naddress and password used when you\ninitially created the ID.', 'Missing fix', 'Missing link'),
	'2591': new SupportCode('REACHED_ASSOCIATION_LIMIT', 'Missing description', 'This Nintendo Network ID has already\nbeen linked to another Wii U console.\n\nPlease select a different Nintendo\nNetwork ID and try again.', 'Missing fix', 'Missing link'),
	'2592': new SupportCode('REACHED_REGISTRATION_LIMIT', 'Missing description', 'At the moment, it is not possible to\nlink a Nintendo Network ID to this\nconsole.\n\nYou have reached the limit for ID\nlinking at this time.\n\nPlease try again later.', 'Missing fix', 'Missing link'),
	'2593': new SupportCode('COPPA_NOT_ACCEPTED', 'Missing description', 'This Nintendo Network ID cannot be\nused because it has not been confirmed\nby a parent or guardian.\n\nPlease have a parent or guardian\nmake a note of the error code and\nvisit support.nintendo.com.', 'Missing fix', 'Missing link'),
	'2594': new SupportCode('PARENTAL_CONTROLS_REQUIRED', 'Missing description', 'Parental Controls restrictions\nmust be set up first.', 'Missing fix', 'Missing link'),
	'2595': new SupportCode('MII_NOT_REGISTERED', 'Missing description', 'You have not registered a Mii.', 'Missing fix', 'Missing link'),
	'2596': new SupportCode('DEVICE_EULA_COUNTRY_MISMATCH', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2597': new SupportCode('PENDING_MIGRATION', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2610': new SupportCode('WRONG_USER_INPUT', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2611': new SupportCode('WRONG_ACCOUNT_PASSWORD', 'Incorrect password', 'Incorrect password.\n\nPlease go to the Wii U Menu and\nenter your password again.', 'Enter your password again or reset your password and try again', 'Missing link'),
	'2612': new SupportCode('WRONG_MAIL_ADDRESS', 'Missing description', 'The e-mail address you entered is not\ncorrect.\n\nPlease check the e-mail address\nyou entered and try again.', 'Missing fix', 'Missing link'),
	'2613': new SupportCode('WRONG_ACCOUNT_PASSWORD_OR_MAIL_ADDRESS', 'Invalid account information provided. Either your username, password, or email address does not match', 'The information entered is not correct.\nYou may have entered the ID of another\nservice.\n\nPlease enter the details again, making\nsure that the Nintendo Network ID,\npassword, and e-mail address are\ncorrect.', 'Enter corrected information and try again', 'Missing link'),
	'2614': new SupportCode('WRONG_CONFIRMATION_CODE', 'The email confirmation code entered does not match your account', 'Missing message', 'Check your confirmation code and try again', 'Missing link'),
	'2615': new SupportCode('WRONG_BIRTH_DATE_OR_MAIL_ADDRESS', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2616': new SupportCode('WRONG_ACCOUNT_MAIL', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2631': new SupportCode('ACCOUNT_ALREADY_DELETED', 'Missing description', 'This user cannot use network services.\n\nThe Nintendo Network ID linked to this\nuser has been deleted.', 'Missing fix', 'Missing link'),
	'2632': new SupportCode('ACCOUNT_ID_CHANGED', 'Missing description', 'Your Nintendo Network ID has changed.\n\nPlease go to the Wii U Menu, check\nyour new ID, and then try again.', 'Missing fix', 'Missing link'),
	'2633': new SupportCode('AUTHENTICATION_LOCKED', 'Missing description', 'Due to repeated incorrect password\nentries, you are temporarily unable\nto sign in to Nintendo Network\n\nPlease try again later.', 'Missing fix', 'Missing link'),
	'2634': new SupportCode('DEVICE_INACTIVE', 'Missing description', 'An error has occurred.\n\nPlease make note of the error code\nand visit support.nintendo.com.', 'Missing fix', 'Missing link'),
	'2635': new SupportCode('COPPA_AGREEMENT_CANCELED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2636': new SupportCode('DOMAIN_ACCOUNT_ALREADY_EXISTS', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2641': new SupportCode('ACCOUNT_TOKEN_EXPIRED', 'The token provided is expired', 'Missing message', 'Log in again or restart your application or console and try again', 'Missing link'),
	'2642': new SupportCode('INVALID_ACCOUNT_TOKEN', 'The login token provided is invalid', 'Missing message', 'Restart your application or console and try again', 'Missing link'),
	'2643': new SupportCode('AUTHENTICATION_REQUIRED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2651': new SupportCode('CONFIRMATION_CODE_EXPIRED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2661': new SupportCode('MAIL_ADDRESS_NOT_VALIDATED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2662': new SupportCode('EXCESSIVE_MAIL_SEND_REQUEST', 'Missing description', 'You cannot perform this operation\nseveral times in a row.\n\nPlease try again later.', 'Missing fix', 'Missing link'),
	'2670': new SupportCode('CREDIT_CARD_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2671': new SupportCode('CREDIT_CARD_GENERAL_FAILURE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2672': new SupportCode('CREDIT_CARD_DECLINED', 'Missing description', 'The use of this credit card has\nbeen stopped.', 'Missing fix', 'Missing link'),
	'2673': new SupportCode('CREDIT_CARD_BLACKLISTED', 'Missing description', 'This credit card cannot be used.\n\nPlease contact your credit-card\nprovider for more information.', 'Missing fix', 'Missing link'),
	'2674': new SupportCode('INVALID_CREDIT_CARD_NUMBER', 'Missing description', 'Please check the credit-card\nnumber and try entering it again.', 'Missing fix', 'Missing link'),
	'2675': new SupportCode('INVALID_CREDIT_CARD_DATE', 'Missing description', 'Please check the credit-card\nexpiration date and try entering\nit again.', 'Missing fix', 'Missing link'),
	'2676': new SupportCode('INVALID_CREDIT_CARD_PIN', 'Missing description', 'Please check the credit-card\nPIN and try entering it again.', 'Missing fix', 'Missing link'),
	'2677': new SupportCode('INVALID_POSTAL_CODE', 'Missing description', 'The information entered is not correct.\nPlease check it and try again.', 'Missing fix', 'Missing link'),
	'2678': new SupportCode('INVALID_LOCATION', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2679': new SupportCode('CREDIT_CARD_DATE_EXPIRED', 'Missing description', 'The credit card has expired.', 'Missing fix', 'Missing link'),
	'2680': new SupportCode('CREDIT_CARD_NUMBER_WRONG', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2681': new SupportCode('CREDIT_CARD_PIN_WRONG', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2800': new SupportCode('BANNED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2801': new SupportCode('BANNED_ACCOUNT', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2802': new SupportCode('BANNED_ACCOUNT_ALL', 'Your PNID is permanently banned from all aspects of the network', 'This Nintendo Network ID\ncannot be used.\n\nPlease make a note of the error code\nand visit support.nintendo.com.', 'Don\'t do whatever you did to get banned', 'Missing link'),
	'2803': new SupportCode('BANNED_ACCOUNT_IN_APPLICATION', 'Your PNID is permanently banned from this application', 'Online services cannot be used.\n\nPlease make a note of the error code\nand visit support.nintendo.com.', 'Don\'t do whatever you did to get banned', 'Missing link'),
	'2804': new SupportCode('BANNED_ACCOUNT_IN_NEX_SERVICE', 'Your PNID is permanently banned from this game', 'Missing message', 'Don\'t do whatever you did to get banned', 'Missing link'),
	'2805': new SupportCode('BANNED_ACCOUNT_IN_INDEPENDENT_SERVICE', 'Your PNID is permanently banned from this service', 'Missing message', 'Don\'t do whatever you did to get banned', 'Missing link'),
	'2811': new SupportCode('BANNED_DEVICE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2812': new SupportCode('BANNED_DEVICE_ALL', 'Your console is permanently banned from all aspects of the network', 'Online services are unavailable\non this console.\n\nPlease make a note of the error code\nand visit support.nintendo.com.', 'Don\'t do whatever you did to get banned', 'Missing link'),
	'2813': new SupportCode('BANNED_DEVICE_IN_APPLICATION', 'Your console is permanently banned from this application', 'Missing message', 'Don\'t do whatever you did to get banned', 'Missing link'),
	'2814': new SupportCode('BANNED_DEVICE_IN_NEX_SERVICE', 'Your console is permanently banned from this game', 'Missing message', 'Don\'t do whatever you did to get banned', 'Missing link'),
	'2815': new SupportCode('BANNED_DEVICE_IN_INDEPENDENT_SERVICE', 'Your console is permanently banned from this service', 'Missing message', 'Don\'t do whatever you did to get banned', 'Missing link'),
	'2821': new SupportCode('BANNED_ACCOUNT_TEMPORARILY', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2822': new SupportCode('BANNED_ACCOUNT_ALL_TEMPORARILY', 'Your PNID is temporarily banned from all aspects of the network', 'Missing message', 'Wait for the ban to expire', 'Missing link'),
	'2823': new SupportCode('BANNED_ACCOUNT_IN_APPLICATION_TEMPORARILY', 'Your PNID is temporarily banned from this application', 'Missing message', 'Wait for the ban to expire', 'Missing link'),
	'2824': new SupportCode('BANNED_ACCOUNT_IN_NEX_SERVICE_TEMPORARILY', 'Your PNID is temporarily banned from this game', 'Missing message', 'Wait for the ban to expire', 'Missing link'),
	'2825': new SupportCode('BANNED_ACCOUNT_IN_INDEPENDENT_SERVICE_TEMPORARILY', 'Your PNID is temporarily banned from this service', 'Missing message', 'Wait for the ban to expire', 'Missing link'),
	'2831': new SupportCode('BANNED_DEVICE_TEMPORARILY', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2832': new SupportCode('BANNED_DEVICE_ALL_TEMPORARILY', 'Your console is temporarily banned from all aspects of the network', 'Missing message', 'Missing fix', 'Wait for the ban to expire'),
	'2833': new SupportCode('BANNED_DEVICE_IN_APPLICATION_TEMPORARILY', 'Your console is temporarily banned from this application', 'Missing message', 'Missing fix', 'Wait for the ban to expire'),
	'2834': new SupportCode('BANNED_DEVICE_IN_NEX_SERVICE_TEMPORARILY', 'Your console is temporarily banned from this game', 'Missing message', 'Missing fix', 'Wait for the ban to expire'),
	'2835': new SupportCode('BANNED_DEVICE_IN_INDEPENDENT_SERVICE_TEMPORARILY', 'Your console is temporarily banned from this service', 'Missing message', 'Missing fix', 'Wait for the ban to expire'),
	'2880': new SupportCode('SERVICE_NOT_PROVIDED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2881': new SupportCode('UNDER_MAINTENANCE', 'The server you requested is under maintenance', 'Due to server maintenance, the service\nyou attempted to access is not available\nat this time.\n\nPlease try again later.', 'Try again later', 'Missing link'),
	'2882': new SupportCode('SERVICE_CLOSED', 'The server you requested is closed and no longer maintained', 'This online service is no longer\navailable.\n\nSorry for the inconvenience.', 'Self host the server or use another hosted instance', 'Missing link'),
	'2883': new SupportCode('NINTENDO_NETWORK_CLOSED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2884': new SupportCode('NOT_PROVIDED_COUNTRY', 'Missing description', 'Online services are not available\nin your country of residence.', 'Missing fix', 'Missing link'),
	'2900': new SupportCode('RESTRICTION_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2901': new SupportCode('RESTRICTED_BY_AGE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2910': new SupportCode('RESTRICTED_BY_PARENTAL_CONTROLS', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2911': new SupportCode('ON_GAME_INTERNET_COMMUNICATION_RESTRICTED', 'Missing description', 'Online interaction in games has been\nrestricted by Parental Controls.', 'Missing fix', 'Missing link'),
	'2931': new SupportCode('INTERNAL_SERVER_ERROR', 'Missing description', 'Unable to connect to the server.\n\nEither the server is experiencing high\ntraffic volumes or a server error has\noccurred. Please try again later.\n\nTo learn more about the server\'s current\nstatus, visit support.nintendo.com.', 'Missing fix', 'Missing link'),
	'2932': new SupportCode('UNKNOWN_SERVER_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2998': new SupportCode('UNAUTHENTICATED_AFTER_SALVAGE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2999': new SupportCode('AUTHENTICATION_FAILURE_UNKNOWN', 'Missing description', 'An error has occurred.\n\nPlease try again later.\n\nIf the problem persists, please\nmake a note of the error code and\nvisit support.nintendo.com.', 'Missing fix', 'Missing link'),
	'9999': new SupportCode('Missing name', 'Missing description', 'An error has occurred.\n\nPlease try again later.\n\nIf the problem persists, please\nmake a note of the error code and\nvisit support.nintendo.com.', 'Missing fix', 'Missing link'),
};
