const SupportCode = require('../../../common/support-code');

module.exports = {
	'1001': new SupportCode('Missing name', 'Missing description', 'A system update is required.\n\nGo to System Settings to perform\na system update.', 'Missing fix', 'Missing link'),
	'1002': new SupportCode('Missing name', 'Missing description', 'You cannot use Miiverse because it has\nbeen restricted in Parental Controls.', 'Missing fix', 'Missing link'),
	'1003': new SupportCode('Missing name', 'Missing description', 'You may not post to Miiverse due to a\nrestriction in Parental Controls.', 'Missing fix', 'Missing link'),
	'1008': new SupportCode('Missing name', 'Missing description', 'Miiverse functions are unavailable\nto this Nintendo Network ID.', 'Missing fix', 'Missing link'),
	'1009': new SupportCode('Missing name', 'Missing description', 'Miiverse functions are unavailable\non this console.', 'Missing fix', 'Missing link'),
	'1901': new SupportCode('Missing name', 'Missing description', 'The community code is incorrect.', 'Missing fix', 'Missing link'),
	'1999': new SupportCode('Missing name', 'Missing description', 'An error has occurred.\n\nPlease try again later.\n\nIf the problem persists, please\nmake a note of the error code and\nvisit support.nintendo.com.', 'Missing fix', 'Missing link'),
	'5001': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5002': new SupportCode('Missing name', 'Missing description', 'You must have started Miiverse\nat least once before you can\nuse this online service.\n\nPlease start Miiverse from\nthe HOME Menu and set up\nyour user information.', 'Missing fix', 'Missing link'),
	'5003': new SupportCode('Missing name', 'Missing description', 'The server is currently undergoing\nmaintenance.\n\nPlease try again later.', 'Missing fix', 'Missing link'),
	'5004': new SupportCode('Missing name', 'Missing description', 'The Miiverse service has ended.\nMiiverse and any software features\nthat make use of Miiverse will no\nlonger be available.\n\nThank you for your interest.', 'Missing fix', 'Missing link'),
	'5005': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5006': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5007': new SupportCode('Missing name', 'Missing description', 'Miiverse functions are unavailable\nto this Nintendo Network ID.\n\nFor details, please start Miiverse.', 'Missing fix', 'Missing link'),
	'5008': new SupportCode('Missing name', 'Missing description', 'You cannot post to Miiverse using\nthis Nintendo Network ID.\n\nFor details, please start Miiverse.', 'Missing fix', 'Missing link'),
	'5009': new SupportCode('Missing name', 'Missing description', 'Miiverse functions are unavailable\non this console.\n\nFor details, please start Miiverse.', 'Missing fix', 'Missing link'),
	'5010': new SupportCode('Missing name', 'Missing description', 'You cannot post to Miiverse\nfrom this console.\n\nFor details, please start Miiverse.', 'Missing fix', 'Missing link'),
	'5011': new SupportCode('Missing name', 'Missing description', 'In order to use this online service,\nthe other person must first set up\nMiiverse.', 'Missing fix', 'Missing link'),
	'5012': new SupportCode('Missing name', 'Missing description', 'The connection with the server was lost.\n\nBefore you can use this online service,\nyou must start Miiverse at least once.\n\nPlease start Miiverse from the\nHOME Menu.', 'Missing fix', 'Missing link'),
	'5901': new SupportCode('Missing name', 'Missing description', 'The text you entered contains\ninappropriate words or phrases.', 'Missing fix', 'Missing link'),
	'5911': new SupportCode('Missing name', 'Missing description', 'You cannot create any more\ncommunities.\n\nTo create a new community, you\nmust delete an existing one first.', 'Missing fix', 'Missing link'),
	'5912': new SupportCode('Missing name', 'Missing description', 'You cannot create a community because\nyou cannot add any more communities\nfor this game to your favorites.\n\nTo create a new community, you must\nremove at least one community for this\ngame from your favorites.', 'Missing fix', 'Missing link'),
	'5913': new SupportCode('Missing name', 'Missing description', 'You cannot create a community because\nyou cannot add any more communities \nto your favorites.\n\nTo create a new community, you must\nremove at least one community from\nyour favorites.', 'Missing fix', 'Missing link'),
	'5914': new SupportCode('Missing name', 'Missing description', 'You cannot add any more communities\nfor this game to your favorites.\n\nTo add a new favorite, you must\nremove at least one community for\nthis game from your favorites.', 'Missing fix', 'Missing link'),
	'5915': new SupportCode('Missing name', 'Missing description', 'You cannot add any more communities\nto your favorites.\n\nTo add a new favorite, you must\nremove at least one community from\nyour favorites.', 'Missing fix', 'Missing link'),
	'5916': new SupportCode('Missing name', 'Missing description', 'Communities that you have created\ncannot be removed from your favorites.', 'Missing fix', 'Missing link'),
	'5917': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5919': new SupportCode('Missing name', 'Missing description', 'The community does not exist.', 'Missing fix', 'Missing link'),
	'5921': new SupportCode('Missing name', 'Missing description', 'No more comments can be added\nto this post.', 'Missing fix', 'Missing link'),
	'5922': new SupportCode('Missing name', 'Missing description', 'This user cannot be followed.', 'Missing fix', 'Missing link'),
	'5925': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5926': new SupportCode('Missing name', 'Missing description', 'You cannot Yeah! your own post.', 'Missing fix', 'Missing link'),
	'5927': new SupportCode('Missing name', 'Missing description', 'You cannot Yeah! this post.', 'Missing fix', 'Missing link'),
	'5928': new SupportCode('Missing name', 'Missing description', 'You cannot add this community to\nyour favorites.', 'Missing fix', 'Missing link'),
	'5929': new SupportCode('Missing name', 'Missing description', 'Either this user does not exist or initial\nsettings haven\'t been configured for\nMiiverse.', 'Missing fix', 'Missing link'),
	'5930': new SupportCode('Missing name', 'Missing description', 'You cannot see this user\'s information\nbecause his or her friend list and\nfollowers are restricted.', 'Missing fix', 'Missing link'),
	'5931': new SupportCode('Missing name', 'Missing description', 'You cannot comment on this post.', 'Missing fix', 'Missing link'),
	'5932': new SupportCode('Missing name', 'Missing description', 'This post does not exist.', 'Missing fix', 'Missing link'),
	'5935': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'9999': new SupportCode('Missing name', 'Missing description', 'Unable to connect to the server.\n\nPlease try again later.\n\nIf the problem persists, please\nmake a note of the error code and\nvisit support.nintendo.com.', 'Missing fix', 'Missing link'),
};