const SupportCode = require('../../../common/support-code');

module.exports = {
	'0006': new SupportCode('Missing name', 'Missing description', 'You do not currently have\nan Internet connection.\n\nPlease try again later.', 'Missing fix', 'Missing link'),
	'0203': new SupportCode('Missing name', 'Missing description', 'A communication error has occurred.\n\nThe network may be busy, or the signal\nstrength may be weak. Make sure there\nare no obstructions between the\nconsole and the wireless router or other\nnetwork device, or adjust the wireless\nchannel in your device\'s settings, and\ntry again.\n\nIf the problem persists, it is possible\nthat the DNS settings are incorrect.\n\nPlease check these settings under the\nInternet option in System Settings.', 'Missing fix', 'Missing link'),
	'0501': new SupportCode('Missing name', 'Missing description', 'Failed to connect to partner\'s device,\nbecause partner temporarily could not\naccept your transmission.\n\nPlease try again later.', 'Missing fix', 'Missing link'),
	'0502': new SupportCode('Missing name', 'Missing description', 'Failed to connect to partner\'s device,\nbecause partner did not respond.\n\nPlease try again later.', 'Missing fix', 'Missing link'),
	'0506': new SupportCode('Missing name', 'Missing description', 'Failed to connect to partner\'s device,\nbecause the current session is full.\n\nPlease try again later.', 'Missing fix', 'Missing link'),
	'0510': new SupportCode('Missing name', 'Missing description', 'Failed to connect to partner\'s device.\n\nPlease try again later.\n\nIf the problem persists, your Internet\nsettings may need to be optimized\nfor connecting to a partner.', 'Missing fix', 'Missing link'),
	'0511': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0512': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0513': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0514': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0515': new SupportCode('Missing name', 'Missing description', 'Failed to connect to partner\'s device.\n\nPlease try again later.\n\nIf the problem persists, your partner\'s\nInternet settings may need to be\noptimized for connecting to you.', 'Missing fix', 'Missing link'),
	'0516': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0517': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0518': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0519': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0520': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0521': new SupportCode('Missing name', 'Missing description', 'Failed to connect to partner\'s device,\nbecause partner did not respond.\n\nPlease try again later.', 'Missing fix', 'Missing link'),
	'0542': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0547': new SupportCode('Missing name', 'Missing description', 'A communication error has occurred.\n\nThe network may be busy, or the signal\nstrength may be weak. Make sure there\nare no obstructions between the\nconsole and the wireless router or other\nnetwork device, or adjust the wireless\nchannel in your device\'s settings, and\ntry again.', 'Missing fix', 'Missing link'),
	'0561': new SupportCode('Missing name', 'Missing description', 'The server is currently undergoing\nmaintenance. We apologize for any\ninconvenience. Please try again later.\n\nIf the problem persists, please\nvisit support.nintendo.com.', 'Missing fix', 'Missing link'),
	'9999': new SupportCode('Missing name', 'Missing description', 'An error has occurred.\n\nPlease try again later.\n\nIf the problem persists, please\nmake a note of the error code and\nvisit support.nintendo.com.', 'Missing fix', 'Missing link'),
};
