const SupportCode = require('../../../common/support-code');

module.exports = {
	'1011': new SupportCode('Missing name', 'Missing description', 'Please insert a disc.', 'Missing fix', 'Missing link'),
	'1013': new SupportCode('Missing name', 'Missing description', 'Connect a USB storage device to one of\nthe USB ports.', 'Missing fix', 'Missing link'),
	'1014': new SupportCode('Missing name', 'Missing description', 'Insert an SD Card into the SD Card slot.', 'Missing fix', 'Missing link'),
	'1021': new SupportCode('Missing name', 'Missing description', 'The disc could not be read.\n\nPress the EJECT Button, remove\nthe disc, and check that the label side\nis facing the proper direction and\ndisplays either the Wii U or Wii logo.', 'Missing fix', 'Missing link'),
	'1023': new SupportCode('Missing name', 'Missing description', 'This USB storage device cannot\nbe used.\n\nFor a list of supported USB\nstorage devices, please visit\nsupport.nintendo.com.', 'Missing fix', 'Missing link'),
	'1024': new SupportCode('Missing name', 'Missing description', 'This SD Card cannot be used.\n\nFor information on supported SD Cards,\nplease visit support.nintendo.com.', 'Missing fix', 'Missing link'),
	'1031': new SupportCode('Missing name', 'Missing description', 'The disc could not be read. It might\nbe dirty.\n\nPress the EJECT Button, remove\nthe disc, and clean it gently, using\na soft cloth to wipe outward from\nthe center.\n\nIf that does not resolve the issue,\nmake a note of the error code and\nvisit support.nintendo.com.', 'Missing fix', 'Missing link'),
	'1044': new SupportCode('Missing name', 'Missing description', 'An error relating to the SD Card has\noccurred.\n\nPlease make a note of the error code,\nremove the SD Card, and then visit\nsupport.nintendo.com.', 'Missing fix', 'Missing link'),
	'1054': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'1063': new SupportCode('Missing name', 'Missing description', 'The USB storage device is\nwrite-protected.\n\nPlease refer to the manual for the\ndevice and disable write-protection.', 'Missing fix', 'Missing link'),
	'1064': new SupportCode('Missing name', 'Missing description', 'This SD Card is write-protected.\n\nPlease move the write-protection\nswitch on the SD Card to the\nunlocked position.', 'Missing fix', 'Missing link'),
	'1071': new SupportCode('Missing name', 'Missing description', 'The disc currently in the console\nis for a different game.\n\nPlease insert the correct disc.', 'Missing fix', 'Missing link'),
	'1090': new SupportCode('Missing name', 'Missing description', 'An error has occurred.\n\nIf there is a disc in your console, press\nthe EJECT Button and remove the disc.\n\nMake a note of the error code and\nturn the Wii U console power off, and\nthen unplug the AC adapter from the\noutlet and visit support.nintendo.com.', 'Missing fix', 'Missing link'),
	'1091': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'1092': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'1093': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'1094': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'1099': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'1999': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2021': new SupportCode('Missing name', 'Missing description', 'The disc could not be read.\n\nPress the EJECT Button, remove\nthe disc, and check that the label side\nis facing the proper direction and\ndisplays either the Wii U or Wii logo.', 'Missing fix', 'Missing link'),
	'2031': new SupportCode('Missing name', 'Missing description', 'The disc could not be read. It might\nbe dirty.\n\nPress the EJECT Button, remove\nthe disc, and clean it gently, using\na soft cloth to wipe outward from\nthe center.\n\nIf that does not resolve the issue,\nmake a note of the error code and\nvisit support.nintendo.com.', 'Missing fix', 'Missing link'),
	'3020': new SupportCode('Missing name', 'Missing description', 'An error has occurred.\n\nIf there is a disc in the console, press\nthe EJECT Button and remove the disc,\nthen turn off the Wii U console and try\nagain later.\n\nIf the problem persists, please make\nnote of the error code, and then turn\noff the console\'s power, unplug the\nWii U console\'s AC adapter from the\noutlet, and visit support.nintendo.com.', 'Missing fix', 'Missing link'),
	'3021': new SupportCode('Missing name', 'Missing description', 'An error has occurred.\n\nIf there is a disc in the console, press\nthe EJECT Button, remove the disc,\nand clean it gently, using a soft cloth\nto wipe outward from the center.\n\nAfter that, turn off the Wii U console\nand try again.\n\nIf the problem persists, please make\nnote of the error code, and then turn\noff the console\'s power, unplug the\nWii U console\'s AC adapter from the\noutlet, and visit support.nintendo.com.', 'Missing fix', 'Missing link'),
	'3022': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3023': new SupportCode('Missing name', 'Missing description', 'An error has occurred.\n\nThe USB storage device may not be\nreceiving enough power.\n\nPlease turn the Wii U console off, and\nthen plug in the USB storage device\'s\nAC adapter (if included).\n\nIf the problem persists, please make\nnote of the error code, and then turn\noff the console\'s power, unplug the\nWii U console\'s AC adapter from the\noutlet, and visit support.nintendo.com.', 'Missing fix', 'Missing link'),
	'3024': new SupportCode('Missing name', 'Missing description', 'An error has occurred.\n\nIf there is an SD Card in your console,\nplease remove it, turn off the console,\nand then try again.\n\nIf the problem persists, please make\nnote of the error code, and then turn\noff the console\'s power, unplug the\nWii U console\'s AC adapter from the\noutlet, and visit support.nintendo.com.', 'Missing fix', 'Missing link'),
	'3029': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3030': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3031': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3032': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3033': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3034': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3039': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3050': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3051': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3052': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3053': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3054': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3059': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3080': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3081': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3082': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3083': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3084': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3089': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3090': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3091': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3092': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3093': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3094': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3099': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3140': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3141': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3142': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3143': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3144': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3149': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3160': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3161': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3162': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3163': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3164': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3169': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3190': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3191': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3192': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3193': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3194': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3199': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3230': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3231': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3232': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3233': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3234': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3239': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3300': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3301': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3302': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3303': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3304': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3309': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3310': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3311': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3312': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3313': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3314': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3319': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3330': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3331': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3332': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3333': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3334': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3339': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3340': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3341': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3342': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3343': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3344': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3349': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3350': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3351': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3352': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3353': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3354': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3359': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3450': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3451': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3452': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3453': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3454': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3459': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3990': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3991': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3992': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3993': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3994': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'3999': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'9999': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
};