const SupportCode = require('../../../common/support-code');

module.exports = {
	'1230': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2008': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2037': new SupportCode('Missing name', 'Missing description', 'The server is currently undergoing\nmaintenance. We apologize for any\ninconvenience. Please try again later.\n\nTo learn more about maintenance,\nvisit support.nintendo.com', 'Missing fix', 'Missing link'),
	'2038': new SupportCode('Missing name', 'Missing description', 'In order to use this service, a system\nupdate is required.\n\nTo perform a system update, select\nSystem Update from Other Settings\nin System Settings', 'Missing fix', 'Missing link'),
	'2043': new SupportCode('Missing name', 'Missing description', 'In order to use this service, a system\nupdate is required.\n\nTo perform a system update, select\nSystem Update from Other Settings\nin System Settings', 'Missing fix', 'Missing link'),
	'2056': new SupportCode('Missing name', 'Missing description', 'There are not enough open blocks\non the SD Card.\n\nUse Data Management in System\nSettings to delete unnecessary\ndata on the SD Card', 'Missing fix', 'Missing link'),
	'2061': new SupportCode('Missing name', 'Missing description', 'Could not access SD Card.\n\nTurn off the system, remove\nand reinsert the SD Card, and\nthen try again', 'Missing fix', 'Missing link'),
	'2062': new SupportCode('Missing name', 'Missing description', 'There are not enough open blocks\nin the System Memory.\n\nUse Data Management in System\nSettings to delete unnecessary\ndata from the System Memory', 'Missing fix', 'Missing link'),
	'2068': new SupportCode('Missing name', 'Missing description', 'The server is currently undergoing\nmaintenance. We apologize for any\ninconvenience. Please try again later.\n\nTo learn more about maintenance,\nvisit support.nintendo.com', 'Missing fix', 'Missing link'),
	'2069': new SupportCode('Missing name', 'Missing description', 'This software is corrupted.\n\nGo to System Settings ⇒ Data \nManagement ⇒ Nintendo 3DS ⇒\nSoftware, delete this data, and\nthen download it again.\n\nIf the problem persists, please\nmake a note of the error code and\nvisit support.nintendo.com', 'Missing fix', 'Missing link'),
	'4017': new SupportCode('Missing name', 'Missing description', 'The activation code could not be\nrecognized. Please check the\ncode and try entering it again.\n\nFor help, visit support.nintendo.com', 'Missing fix', 'Missing link'),
	'4040': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'4069': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'4240': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'4305': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'4320': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5403': new SupportCode('Missing name', 'Missing description', 'Transfers are currently prohibited.\n\nPlease try again later', 'Missing fix', 'Missing link'),
	'5404': new SupportCode('Missing name', 'Missing description', 'No more transfers can be performed', 'Missing fix', 'Missing link'),
	'5542': new SupportCode('Missing name', 'Missing description', 'You have reached the maximum\namount of funds that can be\nadded to your account', 'Missing fix', 'Missing link'),
	'5546': new SupportCode('Missing name', 'Missing description', 'You can\'t purchase any more items.\n\nFor help, visit support.nintendo.com', 'Missing fix', 'Missing link'),
	'5568': new SupportCode('Missing name', 'Missing description', 'This activation code\ncannot be used with your\ncurrent region setting.\n\nPlease check the code\nand try entering it again', 'Missing fix', 'Missing link'),
	'5593': new SupportCode('Missing name', 'Missing description', 'Could not transfer this software.\nPlease try again later.\n\nIf the problem persists, please\nvisit support.nintendo.com', 'Missing fix', 'Missing link'),
	'5602': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5644': new SupportCode('Missing name', 'Missing description', 'You cannot use a credit card with\nthis system.\n\nFor more information, please visit\nsupport.nintendo.com', 'Missing fix', 'Missing link'),
	'5670': new SupportCode('Missing name', 'Missing description', 'You cannot view your Account Activity\nat this time.\n\nPlease try again later', 'Missing fix', 'Missing link'),
	'5687': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5704': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5804': new SupportCode('Missing name', 'Missing description', 'The number you entered\nhas expired', 'Missing fix', 'Missing link'),
	'5811': new SupportCode('Missing name', 'Missing description', 'This activation code has expired', 'Missing fix', 'Missing link'),
	'5815': new SupportCode('Missing name', 'Missing description', 'This activation code has already\nbeen used', 'Missing fix', 'Missing link'),
	'5941': new SupportCode('Missing name', 'Missing description', 'The user name and/or password is\nincorrect.\n\n■Please check your user name and\npassword and try again.\n\n■If you have forgotten your user\nname or password, please visit\nclub.nintendo.com and click on\n"Member Sign In," followed by\n"Forgot username?" or "Forgot\npassword?', 'Missing fix', 'Missing link'),
	'5942': new SupportCode('Missing name', 'Missing description', 'A connection error has occurred, so\nyour user name could not be\nregistered.\nPlease try again later.\n\nIf the problem persists, please\nvisit support.nintendo.com', 'Missing fix', 'Missing link'),
	'5948': new SupportCode('Missing name', 'Missing description', 'Performing this transfer will take\nyour Nintendo eShop funds over\nthe maximum permitted value.\nPlease reduce your funds on\none of the systems and try again', 'Missing fix', 'Missing link'),
	'5958': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5964': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5989': new SupportCode('Missing name', 'Missing description', 'You cannot link your Club Nintendo\naccount to more than eight systems\nin the Nintendo 3DS family', 'Missing fix', 'Missing link'),
	'6402': new SupportCode('Missing name', 'Missing description', 'The user name and/or \npassword is incorrect.\n\n■Please check your user name and\npassword and try again.\n\n■If you have forgotten your user\nname or password, please visit\nclub.nintendo.com and click on\n"Member Sign In," followed by\n"Forgot username?" or "Forgot\npassword?', 'Missing fix', 'Missing link'),
	'6403': new SupportCode('Missing name', 'Missing description', 'Could not register the user name\nyou entered.\n\n■For more information, go to\nclub.nintendo.com', 'Missing fix', 'Missing link'),
	'6499': new SupportCode('Missing name', 'Missing description', 'The Club Nintendo servers are currently\nundergoing maintenance, so your\nuser name could not be registered.\n\nPlease try again later', 'Missing fix', 'Missing link'),
	'6501': new SupportCode('Missing name', 'Missing description', 'This credit card cannot be used.\n\nFor more information, please visit\nsupport.nintendo.com', 'Missing fix', 'Missing link'),
	'6503': new SupportCode('Missing name', 'Missing description', 'The credit-card number you entered is\nnot valid.\n\nPlease confirm the number and try again', 'Missing fix', 'Missing link'),
	'6504': new SupportCode('Missing name', 'Missing description', 'Enter the three-digit security code', 'Missing fix', 'Missing link'),
	'6507': new SupportCode('Missing name', 'Missing description', 'The credit-card details were not entered\ncorrectly.\n\nPlease confirm the details and try again', 'Missing fix', 'Missing link'),
	'6509': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'6511': new SupportCode('Missing name', 'Missing description', 'This credit card cannot be used.\n\nFor more information, please contact\nyour credit-card provider', 'Missing fix', 'Missing link'),
	'6514': new SupportCode('Missing name', 'Missing description', 'The expiration date for this credit card\nis incorrect', 'Missing fix', 'Missing link'),
	'6519': new SupportCode('Missing name', 'Missing description', 'The address you have entered\ndoes not match your credit\ncard\'s billing address.\n\nPlease check the address\nand try again', 'Missing fix', 'Missing link'),
	'7545': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'7550': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'8025': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'8026': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'8029': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
};
