const SupportCode = require('../../../common/support-code');

module.exports = {
	'1001': new SupportCode('Missing name', 'Missing description', 'A system update is required.\n\nTo perform a system update, select\nSystem Update from Other Settings\nin System Settings', 'Missing fix', 'Missing link'),
	'1002': new SupportCode('Missing name', 'Missing description', 'You cannot use Miiverse because it has\nbeen restricted in Parental Controls', 'Missing fix', 'Missing link'),
	'1003': new SupportCode('Missing name', 'Missing description', 'You may not post to Miiverse due to a\nrestriction in Parental Controls', 'Missing fix', 'Missing link'),
	'1008': new SupportCode('Missing name', 'Missing description', 'Miiverse functions are unavailable\nto this Nintendo Network ID', 'Missing fix', 'Missing link'),
	'1009': new SupportCode('Missing name', 'Missing description', 'Miiverse functions are unavailable\non this system', 'Missing fix', 'Missing link'),
	'1901': new SupportCode('Missing name', 'Missing description', 'The community code is incorrect', 'Missing fix', 'Missing link'),
	'2001': new SupportCode('Missing name', 'Missing description', 'Unable to connect to the server.\nPlease try again later.\n\nFor help, visit support.nintendo.com', 'Missing fix', 'Missing link'),
	'5002': new SupportCode('Missing name', 'Juxtaposition account not initialized', 'You must have started Miiverse\nat least once before you can\nuse this online service.\n\nPlease start Miiverse from\nthe HOME Menu and set up\nyour user information', 'Boot the Miiverse applet from the home screen and complete setup', 'Missing link'),
	'5003': new SupportCode('Missing name', 'Juxtaposition is under maintenance', 'The server is currently undergoing\nmaintenance. We apologize for any\ninconvenience. Please try again later.\n\nTo learn more about maintenance,\nvisit support.nintendo.com', 'Try again later', 'Missing link'),
	'5004': new SupportCode('Missing name', 'Juxtaposition is shut down', 'This service has been discontinued.\nThank you for using this service', 'Self host, use another Juxtaposition instance, or use https://github.com/rverseTeam', 'Missing link'),
	'5007': new SupportCode('Missing name', 'Your PNID has been banned from Juxtaposition', 'Miiverse functions are unavailable\nto this Nintendo Network ID.\n\nFor details, please start Miiverse', 'Don\'t do whatever you did to get banned', 'Missing link'),
	'5008': new SupportCode('Missing name', 'Your PNID has been banned from Juxtaposition', 'You cannot post to Miiverse using\nthis Nintendo Network ID.\n\nFor details, please start Miiverse', 'Don\'t do whatever you did to get banned', 'Missing link'),
	'5009': new SupportCode('Missing name', 'Your console has been banned from Juxtaposition', 'Miiverse functions are unavailable\non this system.\n\nFor details, please start Miiverse', 'Don\'t do whatever you did to get banned', 'Missing link'),
	'5010': new SupportCode('Missing name', 'Your console has been banned from Juxtaposition', 'You cannot post to Miiverse from\nthis system.\n\nFor details, please start Miiverse', 'Don\'t do whatever you did to get banned', 'Missing link'),
	'5011': new SupportCode('Missing name', 'Juxtaposition account not initialized', 'In order to use this online service,\nthe other person must first set up\nMiiverse', 'Boot the Miiverse applet from the home screen and complete setup', 'Missing link'),
	'5012': new SupportCode('Missing name', 'Connection is unstable or Juxtaposition account not initialized', 'Disconnected from the server.\n\nYou must have started Miiverse\nat least once before you can\nuse this online service.\n\nPlease start Miiverse from\nthe HOME Menu', 'Boot the Miiverse applet from the home screen and complete setup, then try again', 'Missing link'),
	'5901': new SupportCode('Missing name', 'Content posted contains text not allowed', 'The text you entered contains\ninappropriate words or phrases', 'Edit your post', 'Missing link'),
	'5911': new SupportCode('Missing name', 'Cannot create anymore communities due to max being reached', 'You cannot create any more\ncommunities.\n\nTo create a new community, you\nmust delete an existing one first', 'Delete an existing community', 'Missing link'),
	'5912': new SupportCode('Missing name', 'Cannot create anymore communities due to favorites for this game being full', 'You cannot create a community because\nyou cannot add any more communities\nfor this game to your favorites.\n\nTo create a new community, you must\nremove at least one community for this\ngame from your favorites', 'Remove a community for this game from your favorites', 'Missing link'),
	'5913': new SupportCode('Missing name', 'Cannot create anymore communities due to favorites being full', 'You cannot create a community because\nyou cannot add any more communities \nto your favorites.\n\nTo create a new community, you must\nremove at least one community from\nyour favorites', 'Remove a community from your favorites', 'Missing link'),
	'5914': new SupportCode('Missing name', 'Favorites for this game are full', 'You cannot add any more communities\nfor this game to your favorites.\n\nTo add a new favorite, you must\nremove at least one community for\nthis game from your favorites', 'Remove a community for this game from your favorites', 'Missing link'),
	'5915': new SupportCode('Missing name', 'Community favorites for are full', 'You cannot add any more communities\nto your favorites.\n\nTo add a new favorite, you must\nremove at least one community from\nyour favorites', 'Remove a community from your favorites', 'Missing link'),
	'5916': new SupportCode('Missing name', 'Trying to remove a community you created from your favorites', 'Communities that you have created\ncannot be removed from your favorites', 'Don\'t do that', 'Missing link'),
	'5919': new SupportCode('Missing name', 'Community not found', 'The community does not exist', 'Verify the community you are trying to access exists', 'Missing link'),
	'5921': new SupportCode('Missing name', 'Post cannot receive anymore comments', 'No more comments can be added\nto this post', 'No fix', 'Missing link'),
	'5922': new SupportCode('Missing name', 'Could not follow user', 'This user cannot be followed', 'No fix', 'Missing link'),
	'5926': new SupportCode('Missing name', 'Trying to Yeah! your own post', 'You cannot Yeah! your own post', 'Don\'t do that', 'Missing link'),
	'5927': new SupportCode('Missing name', 'The post being Yeah!ed cannot be Yeah!ed', 'You cannot Yeah! this post', 'Try again later', 'Missing link'),
	'5928': new SupportCode('Missing name', 'Community could not be added to your favorites', 'You cannot add this community to\nyour favorites', 'Missing fix', 'Missing link'),
	'5929': new SupportCode('Missing name', 'Other users Juxtaposition account not initialized', 'Either this user does not exist or initial\nsettings haven\'t been configured for\nMiiverse', 'No fix', 'Missing link'),
	'5930': new SupportCode('Missing name', 'Other users profile is hidden', 'You cannot see this user\'s information\nbecause his or her friend list and\nfollowers are restricted', 'No fix', 'Missing link'),
	'5931': new SupportCode('Missing name', 'Post could not be commented on', 'You cannot comment on this post', 'Try again later', 'Missing link'),
	'5932': new SupportCode('Missing name', 'Post not found', 'Post does not exist', 'Verify the post you are trying to access exists', 'Missing link'),
	'5936': new SupportCode('Missing name', 'Missing description', 'You have exceeded the character limit', 'Missing fix', 'Missing link'),
	'5937': new SupportCode('Missing name', 'Missing description', 'You cannot make any more posts', 'Missing fix', 'Missing link'),
};
