const SupportCode = require('../../../common/support-code');

module.exports = {
	'0006': new SupportCode('Missing name', 'Missing description', 'You do not currently have\nan Internet connection.\n\nPlease try again later', 'Missing fix', 'Missing link'),
	'0203': new SupportCode('Missing name', 'Missing description', 'A communication error has occurred.\n\nThere may be problems with the\nnetwork or the environment. To\nensure an optimal connection\nenvironment, move closer to the\naccess point and make sure that\nthere are no obstructions between\nyour system and the access point.\nIf this does not work, please try\nagain later.\n\nThere is also a possibility that your\nDNS settings are incorrect. Please\nverify them via Internet Settings in\nSystem Settings', 'Missing fix', 'Missing link'),
	'0311': new SupportCode('Missing name', 'Missing description', 'Unable to connect due to the software\nversion being out of date.\n\nA software update is required', 'Missing fix', 'Missing link'),
	'0312': new SupportCode('Missing name', 'Missing description', 'Unable to connect because one or more\nother users are using software that is\nout of date.\n\nOne or more other users must update\ntheir software', 'Missing fix', 'Missing link'),
	'0501': new SupportCode('Missing name', 'Missing description', 'Failed to connect to partner\'s device,\nbecause partner temporarily could not\naccept your transmission.\n\nPlease try again later', 'Missing fix', 'Missing link'),
	'0502': new SupportCode('Missing name', 'Missing description', 'Failed to connect to partner\'s device,\nbecause partner did not respond.\n\nPlease try again later', 'Missing fix', 'Missing link'),
	'0506': new SupportCode('Missing name', 'Missing description', 'Failed to connect to partner\'s device,\nbecause the current session is full.\n\nPlease try again later', 'Missing fix', 'Missing link'),
	'0510': new SupportCode('Missing name', 'Missing description', 'Failed to connect to partner\'s device.\n\nPlease try again later.\n\nIf the problem persists, something in\nyour network environment may be\ncausing connection issues with your\npartner', 'Missing fix', 'Missing link'),
	'0515': new SupportCode('Missing name', 'Missing description', 'Failed to connect to partner\'s device.\n\nPlease try again later.\n\nIf the problem persists, something in\nyour partner\'s network environment\nmay be causing connection issues', 'Missing fix', 'Missing link'),
	'0516': new SupportCode('Missing name', 'Missing description', 'Failed to connect to partner\'s device.\n\nPlease try again later.\n\nIf the problem persists, something\nin your network environment may be\ncausing connection issues with your\npartner', 'Missing fix', 'Missing link'),
	'0521': new SupportCode('Missing name', 'Missing description', 'Failed to connect to partner\'s device,\nbecause partner did not respond.\n\nPlease try again later', 'Missing fix', 'Missing link'),
	'0542': new SupportCode('Missing name', 'Missing description', 'Failed to connect to partner\'s device,\nbecause the current session is full.\n\nPlease try again later', 'Missing fix', 'Missing link'),
	'0547': new SupportCode('Missing name', 'Missing description', 'A communication error has occurred.\n\nThere may be problems with the\nnetwork or the environment. To\nensure an optimal connection\nenvironment, move closer to the\naccess point and make sure that\nthere are no obstructions between\nyour system and the access point.\nIf this does not work, please try\nagain later', 'Missing fix', 'Missing link'),
	'0561': new SupportCode('Missing name', 'Missing description', 'The server is currently undergoing\nmaintenance. We apologize for any\ninconvenience. Please try again later.\n\nTo learn more about maintenance,\nvisit support.nintendo.com', 'Missing fix', 'Missing link'),
	'0701': new SupportCode('Missing name', 'Missing description', 'Unable to connect due to the software\nversion being out of date.\n\nA software update is required', 'Missing fix', 'Missing link'),
	'0702': new SupportCode('Missing name', 'Missing description', 'Unable to connect because one or more\nother users are using software that is\nout of date.\n\nOne or more other users must update\ntheir software', 'Missing fix', 'Missing link'),
};
